# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  # Beta deployment to TestFlight
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Memorize21.xcodeproj")
    changelog = prompt(
      text: "Changelog: ",
      multi_line_end_keyword: "END"
    )
    sync_code_signing(type: "appstore")
    build_app(scheme: "Memorize21")
    upload_to_testflight(changelog: changelog)
  end
  # Cert and Sigh
  desc "Create cert and sigh"
  lane :get_dev_certs do
    cert(
      development: true
    )
    sigh(
      development: true
    )
  end
  # 
  desc "Create and push a new build to the AppStore"
  lane :release do
    #get_push_certificate                                        # will ensure the certificate is valid for at least another 2 weeks, and create a new one if it isn't
    increment_build_number(xcodeproj: "Memorize21.xcodeproj")
    #capture_screenshots                                        # generate new screenshots for the App Store
    changelog = prompt(
      text: "Changelog: ",
      multi_line_end_keyword: "END"
    )
    get_certificates                                            # invokes cert
    get_provisioning_profile                                    # invokes sigh
    sync_code_signing(type: "appstore")                         # see code signing guide for more information
    build_app(scheme: "Memorize21")
    upload_to_app_store                                         # upload your app to App Store Connect
    #slack(message: "Successfully uploaded a new App Store build")
  end
end
